"use client";
import { useEffect, useState } from "react";
import API from "@/lib/api";
import toast from "react-hot-toast";
const money = (n) => `\u20A6${Number(n || 0).toLocaleString()}`;

export default function CustomersPage() {
  const [customers, setCustomers] = useState([]), [search, setSearch] = useState(""), [profile, setProfile] = useState(null);
  const load = async () => { try { setCustomers((await API.get("/customers")).data || []); } catch { toast.error("Failed to load customers"); } };
  useEffect(() => { load(); }, []);
  const open = async (id) => { try { setProfile((await API.get(`/customers/${id}/profile`)).data); } catch (e) { toast.error(e.response?.data?.error || "Failed to load profile"); } };
  const list = customers.filter((c) => [c.name, c.email, c.phone].some((v) => String(v || "").toLowerCase().includes(search.toLowerCase())));
  return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-7xl"><h1 className="text-3xl font-black">Customer Management</h1><p className="mt-2 text-slate-600">Understand purchase behaviour before following up.</p><input className="mt-6 w-full rounded-xl border p-3" placeholder="Search name, email or phone" value={search} onChange={(e) => setSearch(e.target.value)} /><div className="mt-5 overflow-x-auto rounded-2xl bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-100 text-slate-600"><tr><th className="p-4">Customer</th><th className="p-4">Orders</th><th className="p-4">Spent</th><th className="p-4">Last purchase</th><th className="p-4"></th></tr></thead><tbody>{list.map((c) => <tr key={c.id} className="border-t"><td className="p-4"><b>{c.name || "Customer"}</b><br/><span className="text-slate-500">{c.email || c.phone}</span></td><td className="p-4">{c.total_orders}</td><td className="p-4 font-bold text-emerald-700">{money(c.total_spent)}</td><td className="p-4">{c.last_purchase ? new Date(c.last_purchase).toLocaleDateString() : "—"}</td><td className="p-4 text-right"><button onClick={() => open(c.id)} className="rounded-lg bg-slate-950 px-3 py-2 font-bold text-white">View profile</button></td></tr>)}</tbody></table></div>
  {profile && <section className="mt-6 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="flex justify-between gap-4"><div><p className="text-sm font-bold text-emerald-700">{profile.segment}</p><h2 className="text-2xl font-black">Customer: {profile.name}</h2><p className="text-slate-600">{profile.phone} · {profile.email}</p></div><button onClick={() => setProfile(null)} className="font-bold text-slate-500">Close</button></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Orders",profile.total_orders],["Total spent",money(profile.total_spent)],["Wallet",money(profile.wallet)],["Savings",money(profile.savings)],["Active subscriptions",profile.active_subscriptions],["Bulk customer",profile.bulk_customer ? "Yes" : "No"],["BNPL",profile.bnpl_status],["Last purchase",profile.last_purchase ? new Date(profile.last_purchase).toLocaleDateString("en-NG") : "—"]].map(([l,v]) => <div key={l} className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-500">{l}</p><p className="mt-1 font-black">{v}</p></div>)}</div><div className="mt-6 flex flex-wrap gap-3">{[["View Orders",`/admin/orders?customer=${profile.id}`],["Wallet","/admin/wallet"],["Savings","/admin/plans"],["Subscriptions","/admin/plans"],["Support History",`/admin/orders?customer=${profile.id}`]].map(([label, href]) => <a key={label} href={href} className="rounded-lg border border-slate-300 px-4 py-2 font-bold">{label}</a>)}</div></section>}</div></main>;
}
