"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import API from "@/lib/api";
import toast from "react-hot-toast";
import { useCartStore } from "@/lib/cartStore";
const money = (v) => `₦${Number(v || 0).toLocaleString()}`;
const active = new Set(["pending","paid","confirmed","processing","assigned","picked_up","ready_for_delivery","in_transit","near_customer"]);
const label = (s) => ({pending:"Order Received",paid:"Confirmed",confirmed:"Confirmed",processing:"Preparing",assigned:"Ready for Delivery",picked_up:"Ready for Delivery",ready_for_delivery:"Ready for Delivery",in_transit:"Out for Delivery",near_customer:"Out for Delivery",delivered:"Delivered",cancelled:"Cancelled"}[String(s||"").toLowerCase()] || "Order Received");
export default function MyOrdersPage(){
 const [orders,setOrders]=useState([]),[suggestions,setSuggestions]=useState([]),[reminders,setReminders]=useState(true),[filter,setFilter]=useState("all"),[loading,setLoading]=useState(true); const {addToCart,setUser:setCartUser}=useCartStore();
 useEffect(()=>{const load=async()=>{try{const user=JSON.parse(localStorage.getItem("user")||"null");if(!user?.id)return;setCartUser(user);const [orderRes,reminderRes]=await Promise.all([API.get(`/orders/user/${user.id}`),API.get(`/orders/restock-suggestions/${user.id}`)]);const summaries=await Promise.all((orderRes.data||[]).map(async o=>{try{const d=await API.get(`/orders/${o.id}`);return {...o,items:d.data.items||[]};}catch{return {...o,items:[]};}}));setOrders(summaries);setSuggestions(reminderRes.data?.suggestions||[]);setReminders(reminderRes.data?.enabled!==false);}finally{setLoading(false);}};load();},[]);
 const buyAgain=async(s)=>{try{await addToCart(s.product_id,1,null);toast.success(`${s.name} added to your cart`);}catch{toast.error("This item is not currently available");}};
 const toggle=async()=>{const next=!reminders;try{await API.patch("/orders/restock-preferences",{restock_reminders_enabled:next});setReminders(next);if(!next)setSuggestions([]);toast.success(next?"Restock reminders enabled":"Restock reminders disabled");}catch{toast.error("Could not update reminder preference");}};
 const visible=useMemo(()=>orders.filter(o=>filter==="active"?active.has(String(o.status||"").toLowerCase()):filter==="all"||o.status===filter),[orders,filter]);
 return <main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-950 md:px-6"><div className="mx-auto max-w-4xl"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Elohim Grains</p><h1 className="mt-1 text-3xl font-black">My Orders</h1>
 {reminders&&suggestions.length>0&&<section className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-black">Buy Again</h2><p className="text-sm text-slate-600">Gentle reminders based on your delivered purchase history—not an estimate of what you have at home.</p></div><button onClick={toggle} className="text-sm font-bold text-emerald-700">Disable reminders</button></div>{suggestions.map(s=><div key={s.product_id} className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-emerald-200 pt-3"><span><b>Running low on {s.name}?</b><small className="block text-slate-600">You last purchased it {s.days_since_purchase} days ago.</small></span><button onClick={()=>buyAgain(s)} className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-black text-white">BUY AGAIN</button></div>)}</section>}
 <div className="mt-5 flex flex-wrap gap-2">{[["all","All"],["active","Active"],["delivered","Delivered"],["cancelled","Cancelled"]].map(([id,text])=><button key={id} onClick={()=>setFilter(id)} className={`rounded-full px-4 py-2 text-sm font-bold ${filter===id?"bg-emerald-600 text-white":"bg-white ring-1 ring-slate-200"}`}>{text}</button>)}{reminders&&suggestions.length===0&&<button onClick={toggle} className="ml-auto text-sm font-bold text-slate-500">Disable restock reminders</button>}</div>
 {loading?<p className="mt-8 text-slate-500">Loading your orders...</p>:visible.length===0?<div className="mt-8 rounded-2xl bg-white p-8 text-center"><p className="font-bold">No orders found.</p><Link href="/products" className="mt-3 inline-block font-bold text-emerald-700">Shop now</Link></div>:<div className="mt-6 space-y-4">{visible.map(o=><article key={o.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-black">Order #{o.order_number||`EG-${o.id}`}</h2><p className="mt-1 text-sm text-slate-500">{new Date(o.created_at).toLocaleDateString()}</p></div><span className="rounded-full bg-amber-100 px-3 py-1 text-sm font-bold">{label(o.status)}</span></div><div className="mt-4 text-sm">{o.items.map(i=><p key={i.id}>{i.name} {i.weight||""} × {i.quantity}</p>)}</div><p className="mt-4 text-xl font-black">{money(o.total_amount)}</p><div className="mt-4 flex gap-4 text-sm font-black text-emerald-700"><Link href={`/order/${o.id}`}>VIEW ORDER</Link><Link href={`/track/${o.id}`}>TRACK DELIVERY</Link></div></article>)}</div>}</div></main>;
}
