export const policyEffectiveDate = "19 September 2026";

export const policies = {
  privacy: { title: "Privacy Policy", summary: "How Elohim collects, uses, protects and shares customer information.", sections: [["Information we use", "We collect information needed to create an account, process orders, deliver food, provide support, prevent fraud and meet applicable legal obligations. This can include contact details, delivery details, order history, payment references and, where required, verification information."], ["Access and sharing", "Access follows a need-to-know rule. Delivery staff receive only the customer name, address and delivery contact needed to complete a delivery. They do not receive wallet, savings, BNPL or KYC history. We share data only with service providers needed to process payments, deliver orders, host the service or comply with law."], ["Your choices", "You may update profile details, manage optional marketing reminders and contact support about your data. We retain records where needed for orders, financial reconciliation, security and legal obligations."]]},
  terms: { title: "Terms & Conditions", summary: "The rules for using Elohim Grains products and services.", sections: [["Using Elohim", "Provide accurate information, keep your account credentials private and use the platform lawfully. Product availability, prices, delivery coverage and payment options may change before an order is accepted."], ["Orders and payment", "An order is accepted when Elohim confirms it. A payment shown as successful in a browser is not final confirmation; payment is confirmed after backend/provider verification. We may cancel or review an order where pricing, stock, payment or fraud checks identify an issue."], ["Support", "Questions and complaints should be sent through Elohim support or WhatsApp with your order reference."]]},
  delivery: { title: "Delivery Policy", summary: "Clear delivery expectations, fees and confirmation.", sections: [["Fees and timing", "Delivery fees and estimated windows are shown at checkout where available. Bulk or truck-sized orders may require review and a separately confirmed delivery charge before fulfilment."], ["Your responsibilities", "Provide a correct reachable address, phone number and landmark. Be available during the agreed delivery window or arrange an authorised recipient."], ["Confirmation", "Elohim may use delivery milestones and a delivery PIN or other evidence to confirm handover. Report a delivery issue promptly with the order reference."]]},
  refunds: { title: "Refund & Return Policy", summary: "How to request help when an eligible order has an issue.", sections: [["Requesting a refund", "Contact support promptly after identifying a missing, damaged, incorrect or unavailable item. Include your order reference, what happened and supporting details where available."], ["Review", "Refunds are reviewed against the order, delivery record, stock and payment record. Approved refunds are recorded with a transaction reference and processed to the original eligible method or another agreed method where appropriate."], ["Food products", "Because food products are perishable, return eligibility depends on product condition, delivery evidence, food-safety considerations and applicable law. This policy does not remove any mandatory consumer rights."]]},
  wallet: { title: "Wallet Terms", summary: "Rules for using the Elohim Wallet for eligible Elohim transactions.", sections: [["Wallet records", "Wallet activity is recorded in an immutable transaction ledger. The displayed balance is derived from funding, payments, refunds and approved adjustments."], ["Security", "Keep account credentials and any wallet PIN private. Elohim may require recent authentication or additional verification for sensitive actions and may review unusual activity."], ["Availability", "Wallet options, funding methods and eligible purchases are shown in the product at the time of use. A wallet balance is not sales revenue and is handled separately in Elohim records."]]},
  savings: { title: "Savings Terms", summary: "Food-only savings plans held through the Elohim Wallet.", sections: [["Purpose", "Food Savings helps customers set aside money toward eligible food purchases on Elohim. Savings balances are held in the Elohim Wallet and are intended for food purchases, not cash withdrawal."], ["Fees and cancellation", "Any applicable fee, plan terms and cancellation outcome are shown before confirmation. Elohim will not apply a fee that was not disclosed for the selected plan."], ["Important information", "Savings is not represented as an investment, bank deposit or legally protected escrow arrangement. Availability and any required financial disclosures depend on the services Elohim actually offers."]]},
  bnpl: { title: "BNPL Terms", summary: "Eligibility, repayment and responsible use of pay-in-installments options.", sections: [["Eligibility", "BNPL is displayed only after eligibility review under explicit rules. Approval is not automatic and may be limited, declined or reviewed."], ["Before accepting", "Customers must see the amount due today, repayment dates, applicable charges and the total repayment obligation before accepting a BNPL agreement."], ["Repayment", "Pay instalments when due. Missed payments may affect future eligibility and may trigger the actions or charges disclosed in the applicable agreement and required law."]]},
  vendor: { title: "Vendor Terms", summary: "Marketplace rules for verified suppliers selling through Elohim.", sections: [["Approval and catalogue", "Vendors apply, are reviewed and must be approved before publishing. Elohim may require accurate product details, images, units, availability, pricing, origin and fulfilment information."], ["Orders and fulfilment", "Vendors must accept, prepare and fulfil orders within agreed service levels. Elohim may restrict, suspend or remove vendors whose products or fulfilment repeatedly fail standards."], ["Settlement", "Vendor proceeds are calculated after agreed commission and charges. Payouts become eligible only after fulfilment and delivery confirmation, subject to disputes, refunds and the applicable vendor agreement."]]},
  subscriptions: { title: "Subscription Terms", summary: "How recurring food deliveries are scheduled and controlled.", sections: [["Control", "Customers can view, pause, skip, reschedule or cancel an active subscription before its relevant processing deadline."], ["Orders and payment", "Each scheduled delivery remains subject to stock, delivery availability, current pricing and the payment method shown before processing. Elohim will communicate material changes where practical."], ["Delivery", "Subscription deliveries follow the Delivery Policy. Customers must keep their delivery address and contact information current."]]},
};
