"use client";
import { useEffect, useState } from "react";
import API from "@/lib/api";
import toast from "react-hot-toast";
const money = (n) => `\u20A6${Number(n || 0).toLocaleString()}`;

export default function TransactionLedger() {
  const [rows, setRows] = useState([]), [filter, setFilter] = useState(""), [adjustment, setAdjustment] = useState({ userId: "", direction: "credit", amount: "", reason: "" });
  const load = async () => { try { setRows((await API.get("/admin/transaction-ledger")).data.transactions || []); } catch { toast.error("Failed to load ledger"); } };
  useEffect(() => { load(); }, []);
  const adjust = async (event) => { event.preventDefault(); try { const result = await API.post(`/admin/wallet-adjustments/${adjustment.userId}`, { direction: adjustment.direction, amount: Number(adjustment.amount), reason: adjustment.reason }); toast.success(`Adjustment ${result.data.reference} recorded`); setAdjustment({ userId:"",direction:"credit",amount:"",reason:"" }); load(); } catch (e) { toast.error(e.response?.data?.error || "Could not record adjustment"); } };
  const shown = rows.filter((r) => `${r.reference} ${r.type} ${r.customer_name || ""}`.toLowerCase().includes(filter.toLowerCase()));
  return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-widest text-emerald-700">Financial accountability</p><h1 className="mt-1 text-3xl font-black">Transaction Ledger</h1><p className="mt-2 text-slate-600">Every entry has a reference. Customer wallet balances are derived from this ledger, never edited directly.</p><form onSubmit={adjust} className="mt-6 grid gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-5 md:grid-cols-5"><p className="md:col-span-5 font-black">Authorized wallet adjustment</p><input required type="number" min="1" placeholder="Customer ID" value={adjustment.userId} onChange={(e)=>setAdjustment({...adjustment,userId:e.target.value})} className="rounded-lg border p-3"/><select value={adjustment.direction} onChange={(e)=>setAdjustment({...adjustment,direction:e.target.value})} className="rounded-lg border p-3"><option value="credit">Credit</option><option value="debit">Debit</option></select><input required type="number" min="1" placeholder="Amount" value={adjustment.amount} onChange={(e)=>setAdjustment({...adjustment,amount:e.target.value})} className="rounded-lg border p-3"/><input required placeholder="Reason for adjustment" value={adjustment.reason} onChange={(e)=>setAdjustment({...adjustment,reason:e.target.value})} className="rounded-lg border p-3"/><button className="rounded-lg bg-slate-950 px-4 py-3 font-bold text-white">Record adjustment</button></form><input className="mt-6 w-full rounded-xl border p-3" placeholder="Search reference, type or customer" value={filter} onChange={(e)=>setFilter(e.target.value)}/><div className="mt-4 overflow-x-auto rounded-2xl bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-100 text-slate-600"><tr><th className="p-4">Reference</th><th className="p-4">Type</th><th className="p-4">Customer</th><th className="p-4">Amount</th><th className="p-4">Status</th><th className="p-4">Audit detail</th></tr></thead><tbody>{shown.map((r,index)=><tr key={`${r.reference}-${index}`} className="border-t"><td className="p-4 font-mono font-bold">{r.reference}</td><td className="p-4 capitalize">{String(r.type).replace(/_/g," ")}</td><td className="p-4">{r.customer_name || "—"}</td><td className={`p-4 font-bold ${r.direction === "debit" ? "text-red-700" : "text-emerald-700"}`}>{r.direction === "debit" ? "−" : ""}{money(r.amount)}</td><td className="p-4"><span className={`rounded-full px-2 py-1 text-xs font-bold ${r.status === "pending" ? "bg-amber-100 text-amber-700" : "bg-emerald-100 text-emerald-700"}`}>{r.status || "verified"}</span></td><td className="p-4 text-slate-600">{r.reason || r.note || "—"}<br/><span className="text-xs">{r.administrator_name && `By ${r.administrator_name} · `}{new Date(r.created_at).toLocaleString()}</span></td></tr>)}</tbody></table></div></div></main>;
}
