"use client";
import { useEffect, useState } from "react";
import API from "@/lib/api";
import toast from "react-hot-toast";

export default function SubscriptionManagement() {
  const [data, setData] = useState({ subscriptions: [], stats: {} }), [filter, setFilter] = useState("all");
  const load = async () => { try { setData((await API.get("/subscriptions/admin/all")).data); } catch { toast.error("Failed to load subscriptions"); } };
  useEffect(() => { load(); }, []);
  const update = async (id, action) => { try { await API.put(`/subscriptions/${id}/${action}`); toast.success(`Subscription ${action}d`); load(); } catch { toast.error("Could not update subscription"); } };
  const shown = data.subscriptions.filter((s) => filter === "all" || s.status === filter);
  const cards = [["Active subscriptions",data.stats.active],["Due today",data.stats.due_today],["Due this week",data.stats.due_week],["Failed payments",data.stats.failed_payments],["Paused",data.stats.paused]];
  return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-widest text-emerald-700">Forecasted fulfilment</p><h1 className="mt-1 text-3xl font-black">Subscription Management</h1><p className="mt-2 text-slate-600">Plan inventory and delivery capacity from customers’ scheduled household and business restocks.</p><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{cards.map(([l,v])=><div key={l} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><p className="text-sm font-bold text-slate-500">{l}</p><p className="mt-2 text-3xl font-black">{v || 0}</p></div>)}</div><div className="mt-6 flex gap-2"><button onClick={()=>setFilter("all")} className={`rounded-full px-4 py-2 font-bold ${filter==="all"?"bg-emerald-600 text-white":"bg-white"}`}>All</button><button onClick={()=>setFilter("active")} className={`rounded-full px-4 py-2 font-bold ${filter==="active"?"bg-emerald-600 text-white":"bg-white"}`}>Active</button><button onClick={()=>setFilter("paused")} className={`rounded-full px-4 py-2 font-bold ${filter==="paused"?"bg-emerald-600 text-white":"bg-white"}`}>Paused</button></div><div className="mt-4 overflow-x-auto rounded-2xl bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-100 text-slate-600"><tr><th className="p-4">Customer</th><th className="p-4">Products</th><th className="p-4">Frequency</th><th className="p-4">Next delivery</th><th className="p-4">Payment</th><th className="p-4">Status</th><th className="p-4"></th></tr></thead><tbody>{shown.map((s)=><tr key={s.id} className="border-t"><td className="p-4"><b>{s.customer_name}</b><br/><span className="text-slate-500">{s.customer_phone || s.customer_email}</span></td><td className="p-4">{s.product_name}{s.weight ? ` — ${s.weight}` : ""}<br/><span className="text-slate-500">Qty: {s.quantity}</span></td><td className="p-4 capitalize">{s.plan === "biweekly" ? "Every 2 weeks" : s.plan}</td><td className="p-4">{new Date(s.next_delivery).toLocaleDateString("en-NG")}</td><td className="p-4">{Number(s.failed_payments) > 0 ? <span className="font-bold text-red-700">{s.failed_payments} failed</span> : <span className="text-emerald-700">Current</span>}</td><td className="p-4"><span className={`rounded-full px-2 py-1 text-xs font-bold ${s.status === "active" ? "bg-emerald-100 text-emerald-700" : "bg-slate-200 text-slate-700"}`}>{s.status}</span></td><td className="p-4">{s.status === "active" ? <button onClick={()=>update(s.id,"pause")} className="font-bold text-amber-700">Pause</button> : <button onClick={()=>update(s.id,"resume")} className="font-bold text-emerald-700">Resume</button>}</td></tr>)}</tbody></table></div></div></main>;
}
