"use client";
import { useEffect, useState } from "react";
import API from "@/lib/api";
import toast from "react-hot-toast";
const money = (v) => `₦${Number(v || 0).toLocaleString()}`;

export default function SuppliersPage() {
  const [data, setData] = useState({ suppliers: [], purchases: [], products: [], totals: {} });
  const [supplier, setSupplier] = useState({ business_name: "", contact_name: "", phone: "", location: "", categories: "", payment_terms: "" });
  const [purchase, setPurchase] = useState({ supplier_id: "", product_id: "", quantity: "", unit_cost: "", expected_date: "" });
  const load = async () => { try { const r = await API.get("/suppliers/admin/overview"); setData(r.data); } catch { toast.error("Could not load suppliers"); } };
  useEffect(() => { load(); }, []);
  const createSupplier = async (e) => { e.preventDefault(); try { await API.post("/suppliers/admin", supplier); toast.success("Supplier added"); setSupplier({ business_name:"",contact_name:"",phone:"",location:"",categories:"",payment_terms:"" }); load(); } catch (err) { toast.error(err.response?.data?.error || "Could not add supplier"); } };
  const createPurchase = async (e) => { e.preventDefault(); try { await API.post("/suppliers/admin/purchase-orders", purchase); toast.success("Supplier purchase order created"); setPurchase({ supplier_id:"",product_id:"",quantity:"",unit_cost:"",expected_date:"" }); load(); } catch (err) { toast.error(err.response?.data?.error || "Could not create purchase order"); } };
  const update = async (id, field, value) => { try { await API.patch(`/suppliers/admin/purchase-orders/${id}`, { [field]: value }); toast.success("Purchase order updated"); load(); } catch (err) { toast.error(err.response?.data?.error || "Could not update purchase order"); } };
  const receive = async (id) => { try { await API.post(`/suppliers/admin/purchase-orders/${id}/receive`); toast.success("Goods received into Elohim inventory; acquisition cost updated"); load(); } catch (err) { toast.error(err.response?.data?.error || "Could not receive goods"); } };
  return <main><h1 className="text-2xl font-black text-slate-950">Supplier Management</h1><p className="mt-1 text-slate-600">Suppliers sell stock to Elohim. They are separate from marketplace vendors and do not receive marketplace commissions or vendor payouts.</p>
    <div className="mt-5 grid gap-4 md:grid-cols-4">{[["Active suppliers",data.totals.suppliers],["Procurement commitment",money(data.totals.procurement_commitment)],["Stock receipts",data.totals.received_orders],["Supplier payments due",money(data.totals.unpaid_supplier_balance)]].map(([l,v])=><div key={l} className="rounded bg-white p-4 shadow"><p className="text-sm text-slate-500">{l}</p><p className="mt-1 text-xl font-black">{v || 0}</p></div>)}</div>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><form onSubmit={createSupplier} className="rounded bg-white p-5 shadow"><h2 className="font-bold">Add supplier</h2>{[["business_name","Business name"],["contact_name","Contact name"],["phone","Phone"],["location","Location"],["categories","Categories"],["payment_terms","Payment terms"]].map(([key,label])=><label key={key} className="mt-3 block text-sm font-bold">{label}<input required={key==="business_name"} value={supplier[key]} onChange={e=>setSupplier({...supplier,[key]:e.target.value})} className="mt-1 w-full rounded border p-2" /></label>)}<button className="mt-4 rounded bg-emerald-700 px-4 py-2 font-bold text-white">Save supplier</button></form>
      <form onSubmit={createPurchase} className="rounded bg-white p-5 shadow"><h2 className="font-bold">New supplier purchase order</h2><label className="mt-3 block text-sm font-bold">Supplier<select required value={purchase.supplier_id} onChange={e=>setPurchase({...purchase,supplier_id:e.target.value})} className="mt-1 w-full rounded border p-2"><option value="">Select supplier</option>{data.suppliers.map(s=><option key={s.id} value={s.id}>{s.business_name}</option>)}</select></label><label className="mt-3 block text-sm font-bold">Elohim inventory product<select required value={purchase.product_id} onChange={e=>setPurchase({...purchase,product_id:e.target.value})} className="mt-1 w-full rounded border p-2"><option value="">Select product</option>{data.products.map(p=><option key={p.id} value={p.id}>{p.name} · current stock {p.stock_quantity || 0}</option>)}</select></label>{[["quantity","Quantity"],["unit_cost","Unit cost"],["expected_date","Expected date"]].map(([key,label])=><label key={key} className="mt-3 block text-sm font-bold">{label}<input required type={key==="expected_date"?"date":"number"} value={purchase[key]} onChange={e=>setPurchase({...purchase,[key]:e.target.value})} className="mt-1 w-full rounded border p-2" /></label>)}<button className="mt-4 rounded bg-slate-900 px-4 py-2 font-bold text-white">Create purchase order</button></form></div>
    <section className="mt-6 rounded bg-white p-5 shadow"><h2 className="font-bold">Supplier purchase orders</h2>{data.purchases.map(p=><div key={p.id} className="mt-3 flex flex-wrap items-center justify-between gap-3 border-b pb-3"><span><b>{p.reference}</b> · {p.business_name} · {p.product_name} × {p.quantity}<small className="block text-slate-500">Cost {money(p.unit_cost)} each · acquisition total {money(p.total_cost)}</small></span><span>{p.status} · supplier payment {p.payment_status}</span><div className="flex gap-2"><select value={p.status} onChange={e=>update(p.id,"status",e.target.value)} className="rounded border p-2">{["draft","ordered","received","cancelled"].map(x=><option key={x}>{x}</option>)}</select><select value={p.payment_status} onChange={e=>update(p.id,"payment_status",e.target.value)} className="rounded border p-2">{["unpaid","part_paid","paid"].map(x=><option key={x}>{x}</option>)}</select>{p.status !== "received" && <button onClick={()=>receive(p.id)} className="rounded bg-emerald-700 px-3 text-xs font-bold text-white">Receive goods</button>}</div></div>)}{!data.purchases.length && <p className="mt-3 text-sm text-slate-500">No supplier purchase orders yet.</p>}</section>
  </main>;
}
