"use client";
import { useEffect, useState } from "react";
import API from "@/lib/api";
import toast from "react-hot-toast";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
const money = (n) => `\u20A6${Number(n || 0).toLocaleString()}`;

export default function Analytics() {
  const [data,setData]=useState(null);
  useEffect(()=>{API.get("/admin/analytics").then((r)=>setData(r.data)).catch(()=>toast.error("Failed to load analytics"));},[]);
  if(!data) return <div className="p-6">Loading analytics…</div>;
  const summary=data.summary||{}, delivery=data.delivery||{}, channels=data.revenue_by_channel||[];
  const cards=[["Revenue",money(summary.revenue)],["Orders",summary.orders||0],["Average order value",money(summary.average_order_value)],["Delivered",delivery.delivered||0],["Delivery failed",delivery.failed||0],["Subscription revenue",money(channels.find(x=>x.name==="Subscription")?.revenue)]];
  return <main className="space-y-6"><div><p className="text-xs font-black uppercase tracking-widest text-emerald-700">Business intelligence</p><h1 className="mt-1 text-3xl font-black">Analytics</h1><p className="mt-2 text-slate-600">Operational performance first; charts second.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{cards.map(([l,v])=><div key={l} className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-sm font-bold text-slate-500">{l}</p><p className="mt-2 text-2xl font-black">{v}</p></div>)}</div><div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-black">Revenue and Orders — Daily</h2><ResponsiveContainer width="100%" height={280}><LineChart data={data.daily}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day" tickFormatter={(v)=>new Date(v).toLocaleDateString("en-NG",{day:"numeric",month:"short"})}/><YAxis/><Tooltip/><Legend/><Line dataKey="revenue" stroke="#059669"/><Line dataKey="orders" stroke="#2563eb"/></LineChart></ResponsiveContainer></section><section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-black">Revenue by category</h2><ResponsiveContainer width="100%" height={280}><BarChart data={data.revenue_by_category}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="revenue" fill="#059669"/></BarChart></ResponsiveContainer></section></div><div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-black">Top products</h2>{data.top_products.map((p,i)=><div key={p.name} className="mt-3 flex justify-between border-b pb-2"><span>{i+1}. {p.name} <small className="text-slate-500">({p.units} units)</small></span><b>{money(p.revenue)}</b></div>)}</section><section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-black">Customer and channel mix</h2>{channels.map((x)=><p key={x.name} className="mt-3 flex justify-between"><span>{x.name}</span><b>{money(x.revenue)}</b></p>)}<hr className="my-4"/>{Object.entries(data.customers||{}).map(([name,count])=><p key={name} className="mt-2 flex justify-between"><span>{name} customers</span><b>{count}</b></p>)}<hr className="my-4"/><p>Out for delivery: <b>{delivery.out_for_delivery||0}</b></p></section></div><section className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><h2 className="font-black">Gross profit</h2><p className="mt-2 text-slate-700">{data.gross_profit_note}</p></section></main>;
}
